import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { createTaskCard } from "../scripts/lib/task-card.mjs";
import { skillVersion, theme } from "../scripts/lib/config.mjs";
import { CURRENT_PLANNING_SCHEMA_VERSION, CURRENT_SLIDE_IR_VERSION } from "../scripts/lib/ir-version.mjs";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const skill = fs.readFileSync(path.join(root, "SKILL.md"), "utf8"), routing = fs.readFileSync(path.join(root, "references/expression-routing.md"), "utf8"), workflow = fs.readFileSync(path.join(root, "references/workflow.md"), "utf8"), quality = fs.readFileSync(path.join(root, "references/quality-gates.md"), "utf8");
assert.match(skill, /sole human work authority/);
assert.match(skill, /does not require that Skill/);
assert.match(skill, /Do not generate draft HTML/);
assert.match(skill, /Visual QA may request `expression-review-required`/);
assert.match(skill, /Aggregation is not summarization/);
assert.match(skill, /Page Evidence Bundle/);
assert.match(workflow, /actual final PPT pages/);
assert.match(workflow, /required-visible/);
assert.match(routing, /not mechanical one-to-one mappings|candidates, not mechanical/i);
assert.match(quality, /visible decision completeness/);
assert.match(quality, /Content.*Source model or planner/s);
assert.equal(theme.themeVersion, "mint-fresh-2/1");
assert.equal(theme.semanticColors.actual, theme.palette.mint);
assert.ok(theme.chartTypographyPt.axis >= 15 && theme.chartTypographyPt.dataLabel >= 16 && theme.chartTypographyPt.legend >= 15);
const card = createTaskCard({ reportId: "weekly-review", title: "经营例会", sections: [{ id: "product", title: "产品", owner: "A", order: 1, outlineItems: ["1"] }] });
assert.equal(card.schemaVersion, "2.0");
assert.equal(card.requiredSkill, "mint-report-ppt");
assert.equal(card.skillVersion, skillVersion);
assert.equal(card.planningSchemaVersion, CURRENT_PLANNING_SCHEMA_VERSION);
assert.equal(card.slideIrVersion, CURRENT_SLIDE_IR_VERSION);
assert.equal(card.allowAppendix, false);
assert.equal(card.publication.primary, "pptx");
assert.equal(card.publication.final, "read-only-html");
assert.equal("htmlCoreVersion" in card, false);
console.log(JSON.stringify({ passed: true, tests: 23 }));
