import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {createRequire} from 'node:module';
import {theme} from '../scripts/lib/config.mjs';
import {planAndMeasureOutline,applyDomLayout} from '../scripts/lib/dom-layout-extractor.mjs';
import {renderPresentation,exportPresentation} from '../scripts/lib/ppt-renderer.mjs';
import {inspectPptxPackage} from '../scripts/lib/pptx-metadata.mjs';
import {nativeDesignPages} from '../scripts/lib/design-intent.mjs';
import {applyDesignBriefs,designExecutionIssues} from '../scripts/lib/execution-brief.mjs';
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'mint-design-brief-'));
// Complete synthetic evidence, not a new Planner run or mentor acceptance.
const modules=[{id:'profiles',type:'diagram',semanticRole:'primaryEvidence',expression:{type:'diagram',variant:'entity-comparison'},data:{nodes:[{id:'entity',entity:true,label:'示例对象',metrics:[{label:'预计规模',value:'688',unit:'亿元'}],secondaryMetrics:[{label:'基准',value:'120',unit:'亿元'}],text:'此处为指标层级专项回归，不代表实际业务数据。'}],edges:[]}},
 {id:'details',type:'table',semanticRole:'supportingEvidence',data:{headers:['项目','计划数量','适用范围'],rows:Array.from({length:12},(_,i)=>['事项'+(i+1),String(i+1),'试点范围'])}}];
const scene={flow:'vertical',regions:modules.map(m=>({id:m.id,role:'primary',relation:'stack',weight:'natural',moduleIds:[m.id]})),readingOrder:modules.map(m=>m.id)};
const metricEmphasis=[{moduleId:'profiles',nodeId:'entity',field:'metric-0',priority:'P0'}];
const brief={decisionSystems:[{id:'D'}],designBriefs:[{id:'story',decisionIds:['D'],compositionPolicy:'flexible',scenePlan:scene,carriers:[{moduleId:'profiles',priority:'P0'},{moduleId:'details',priority:'P1'}],metricEmphasis,directorPlan:{fiveSecondMessage:'预计规模与配套计划在同页核对',visualThesis:'核心规模与配套明细共同证明计划完整性',expectedFirstFocus:{objectRef:'profiles/entity/metric-0',reason:'规模是管理层第一判断'},completeComposition:{flow:'banded',bands:[{id:'evidence',share:[75,88],columns:[2,3],moduleRefs:['profiles','details']}]},alternativeCompositions:[{flow:'banded',bands:[{id:'focus',share:[28,36],columns:[1],moduleRefs:['profiles']},{id:'detail',share:[52,64],columns:[1],moduleRefs:['details']}]}],carrierBindings:[{moduleId:'profiles',expression:'entity-comparison',regionId:'evidence',priority:'P0',visualTreatment:'hero-metric',copyBudget:{maxLines:5}},{moduleId:'details',expression:'table',regionId:'evidence',priority:'P1',visualTreatment:'natural-table',copyBudget:{maxLines:3}}],metricEmphasis,semanticColors:[{targetId:'profiles',role:'highlight'}],bodyProof:[{moduleRefs:['profiles','details'],reason:'核心规模与逐项计划共同支撑标题'}],whitespaceIntent:{intentional:false,reason:null}}}]};
const slides=applyDesignBriefs([{id:'test',role:'content',sectionId:'s',outlineItem:'1',decisionUnit:'D',claim:'预计规模与配套计划在同页核对',modules}],brief);
const measured=await planAndMeasureOutline({slides,executionBrief:brief},theme,path.join(dir,'canvas.html'),path.join(dir,'render'));
fs.writeFileSync(path.join(dir,'capacity.json'),JSON.stringify(measured.measurements,null,2));
assert.equal(measured.ir.slides.length,1,dir);assert.deepEqual(measured.manifest.issues,[]);
assert.ok(measured.measurements.some(a=>a.variant==='director-alternative'),'Test a genuinely different layout');
const leaves=measured.manifest.slides[0].modules.flatMap(m=>m.textObjects),main=leaves.find(t=>t.metricPriority==='P0'&&t.metricPart==='value'),unit=leaves.find(t=>t.metricPriority==='P0'&&t.metricPart==='annotation'),secondary=leaves.find(t=>t.metricPriority==='P2'&&t.metricPart==='value');
assert.ok(main&&unit&&secondary);assert.ok(main.fontSizePx>unit.fontSizePx&&main.fontSizePx>secondary.fontSizePx);
const resolved=applyDomLayout(measured.ir,measured.manifest),{presentation}=await renderPresentation(resolved,theme),file=path.join(dir,'native.pptx');await exportPresentation(presentation,file);
const pkg=await inspectPptxPackage(file),xml=await pkg.zip.file(pkg.slides[0]).async('string');
const native=nativeDesignPages([xml],['test']);
assert.deepEqual(designExecutionIssues(resolved,measured.manifest,native),[]);
const profileManifest=measured.manifest.slides[0].modules.find(m=>m.id==='profiles');
assert.equal(profileManifest.directorTreatment,'hero-metric');
assert.equal(profileManifest.semanticColorRole,'highlight');
const wrong=structuredClone(native);wrong[0].objects.filter(o=>o.name.includes('metric-0|metric-part:value')).forEach(o=>{o.fontSizesPx=[12];});
assert.ok(designExecutionIssues(resolved,measured.manifest,wrong).some(i=>i.includes('DESIGN_NATIVE_METRIC_SIZE_CHANGED')),'A named object with the wrong actual font cannot pass');
assert.equal(pkg.fullSlideImages.length,0);
for(const value of ['688','120','亿元','事项12','试点范围']) assert.ok(pkg.visibleText.includes(value),value);
const target=xml.match(/<p:sp>[^]*?design-target:profiles%2Fentity%2Fmetric-0\|metric-part:value[^]*?<\/p:sp>/)?.[0];
assert.ok(target&&target.includes('688'),'Native metric binding preserves editable value');
const require=createRequire(path.join(process.env.RUNTIME_NODE_MODULES,'package.json'));
const {FileBlob,PresentationFile}=await import(require.resolve('@oai/artifact-tool'));
const imported=await PresentationFile.importPptx(await FileBlob.load(file));
const png=await imported.export({slide:imported.slides.items[0],format:'png',scale:1});
fs.writeFileSync(path.join(dir,'native.png'),new Uint8Array(await png.arrayBuffer()));
const evidence={dir,pages:measured.ir.slides.length,selected:measured.ir.slides[0].measuredSceneVariant,completeAttempts:measured.measurements.filter(a=>a.phase==='complete').map(a=>({variant:a.variant,passed:a.passed,equivalentTo:a.equivalentTo})),fontPx:{main:main.fontSizePx,unit:unit.fontSizePx,secondary:secondary.fontSizePx},scope:'synthetic browser/native regression, not fresh Planner proof'};
fs.writeFileSync(path.join(dir,'result.json'),JSON.stringify(evidence,null,2));console.log(JSON.stringify(evidence));
