import assert from 'node:assert/strict';
import {regulatoryFixture} from './fixtures/design-intent.mjs';
import {narrativeSupport,validateDesignLedger,auditDesignRequirements,executiveReviewIssues,goldenDesignDimensions} from '../scripts/lib/design-intent.mjs';
import {classifySlideComposition} from '../scripts/lib/composition-classifier.mjs';
import {resolveSlideExpressions} from '../scripts/lib/expression-router.mjs';
import {createTaskCard,resolveWorkPackage} from '../scripts/lib/task-card.mjs';
import {planOutlinePages} from '../scripts/lib/outline-planner.mjs';
import {outlineIntegrityIssues} from '../scripts/lib/outline-integrity.mjs';
import {nativeDesignPages} from '../scripts/lib/design-intent.mjs';
import {applyStylePrior} from '../scripts/lib/style-prior.mjs';
import {theme} from '../scripts/lib/config.mjs';
const ir=regulatoryFixture(), slide=ir.slides[0];
assert.equal(narrativeSupport(slide).valid,true);
assert.deepEqual(validateDesignLedger(ir),[]);
assert.equal(auditDesignRequirements(ir,{slides:[]}).passed,false);
assert.equal(executiveReviewIssues(null,[slide.id])[0],'EXECUTIVE_REVIEW_REQUIRED');
const resolved=resolveSlideExpressions(classifySlideComposition(slide));
assert.equal(resolved.modules[1].expression.variant,'critical-path-with-parallel-options');
assert.equal(resolved.modules[2].expression.variant,'entity-comparison');
for(const mutate of [s=>{delete s.modules[1].data.nodes[1].timeRange;},s=>{s.modules[1].data.edges[1].relationship='parallel';},s=>{s.modules[1].data.lanes[1].relationship='dependency';}]) {
  const bad=structuredClone(slide);mutate(bad);assert.equal(narrativeSupport(bad).valid,false);assert.equal(classifySlideComposition(bad).compositionClassification.narrativeAccepted,false);
}
const card=createTaskCard({reportId:'r',title:'Test',sections:[{sectionId:'s1',owner:'刘屹',title:'a',outlineItems:['1']},{sectionId:'s2',owner:'B',title:'b',outlineItems:['2']},{sectionId:'s3',owner:'刘屹',title:'c',outlineItems:['3']}]});
assert.deepEqual(resolveWorkPackage(card,'刘屹').sectionIds,['s1','s3']);
assert.deepEqual(resolveWorkPackage(card,'s1').sectionIds,['s1']);
assert.equal(card.presentationBrief.decisionFirst,true);
const one={...slide,designRequirementRefs:[],visualNarrative:undefined,modules:[{id:'m1',text:'甲',type:'text'}]},two={...one,id:'other',outlineItem:'2',modules:[{id:'m2',text:'乙',type:'text'}]};
const merged=await planOutlinePages([one,two],async()=>({passed:true}));
assert.equal(merged.slides.length,1);assert.deepEqual(merged.slides[0].outlineItems,['1','2']);
const continued=await planOutlinePages([one,two,{...two,id:'third',decisionUnit:'other-decision',modules:[{id:'m3',type:'text',text:'丙'}]}],async()=>({passed:true}));
assert.deepEqual(outlineIntegrityIssues(continued.slides),[]);
const focusIr={slides:[{id:'s'}],designRequirements:[{id:'f',scope:'slide',slideId:'s',strength:'hard',type:'focus',requirement:'focus main',targetId:'main',expectedText:'100'}]};
assert.equal(auditDesignRequirements(focusIr,{slides:[{slideId:'s',modules:[{id:'main',priority:'P2',text:'100'},{id:'other',priority:'P1',text:'100',textObjects:[{text:'100',bold:true}]}]}]}).passed,false);
const arrowIr={slides:[{id:'s'}],designRequirements:[{id:'d',scope:'slide',slideId:'s',strength:'hard',type:'dependency',requirement:'A to B',targetId:'e',from:'A',to:'B'}]};
const arrowManifest={slides:[{slideId:'s',modules:[{primitives:[{primitive:'dependency-edge',bindingId:'m/e',edgeId:'e',from:'A',to:'B'}]}]}]};
const fake='<p:sp><p:cNvPr name="mint|primitive:dependency-edge|binding:m%2Fe"/></p:sp>';
assert.equal(auditDesignRequirements(arrowIr,arrowManifest,{nativePages:nativeDesignPages([fake],['s'])}).passed,false);
assert.ok(executiveReviewIssues({status:'reviewed',slides:[],issues:[{ownerLayer:'canvas'}]},[]).includes('EXECUTIVE_REVIEW_UNRESOLVED'));
const style={kind:'mint-style-prior',version:1,approved:true,fonts:{cjk:'Microsoft YaHei'},palette:{ink:'#182C40'},typographyPt:{contentTitle:[28,32]}};
assert.equal(applyStylePrior(theme,style).typographyPt.contentTitle[0],28);
assert.throws(()=>applyStylePrior(theme,{...style,typographyPt:{body:[8,10]}}),/STYLE_READABILITY_FLOOR/);
assert.throws(()=>applyStylePrior(theme,{...style,slots:['chart']}),/STYLE_CONTENT_SLOTS_FORBIDDEN/);
await assert.rejects(()=>planOutlinePages([slide],async()=>({passed:false,issues:['overflow']}),{designRequirements:ir.designRequirements}),/HARD_SINGLE_PAGE_CAPACITY/);
console.log('design-intent: contracts, fallback, owner scope, merge and blocking passed');
const dimensions=['firstFocus','bodyProvesTitle','relationships','space','carrierSuitability','hierarchy','readingOrder','relationshipFidelity','semanticProximity'];
const {humanCopyChecks}=await import('../scripts/lib/presentation-copy.mjs');
const passPage={slideId:'p',actualFirstFocus:'Main metric',...Object.fromEntries(dimensions.map(d=>[d,'pass'])),goldenScores:Object.fromEntries(Object.entries(goldenDesignDimensions).map(([k,max])=>[k,max])),goldenScore:100,humanPresentationCopy:{...Object.fromEntries(humanCopyChecks.map(d=>[d,'pass'])),evidence:'Reviewed synthetic prose, names and values, no instruction text.'}};
assert.ok(executiveReviewIssues({status:'reviewed',slides:[passPage]},['p']).some(i=>i.startsWith('EXECUTIVE_REVIEW_OBSERVATION_REQUIRED')));
const reviewed={status:'reviewed',reviewContext:'independent-context',generatorExplanationUsed:false,slides:[{...passPage,evidence:'Main metric precedes supporting comparison.'},{...passPage,slideId:'q',evidence:'Second decision has distinct evidence.'}]};
assert.ok(executiveReviewIssues(reviewed,['p','q'],[]).some(i=>i.startsWith('CHAPTER_REVIEW_REQUIRED')));
reviewed.chapter={slideIds:['p','q'],titleChain:'Decision then separate action',crossDecisionEvidence:'Adjacent content reviewed together.',goldenAverage:100,adjacentPages:[{before:'p',after:'q',reason:'measured-capacity',evidence:'Whole candidate overflowed.'}]};
assert.ok(executiveReviewIssues(reviewed,['p','q'],[]).some(i=>i.startsWith('CHAPTER_BOUNDARY_UNPROVEN')));
reviewed.chapter.adjacentPages[0].capacityAttemptIds=['attempt-1'];
assert.deepEqual(executiveReviewIssues(reviewed,['p','q'],[]),[]);
