import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {createRequire} from 'node:module';
import {artifactLayoutIssues} from '../scripts/lib/artifact-layout.mjs';
import {regulatoryFixture} from './fixtures/design-intent.mjs';
import {classifySlideComposition} from '../scripts/lib/composition-classifier.mjs';
import {resolveSlideExpressions} from '../scripts/lib/expression-router.mjs';
import {allocateSlideEvidence} from '../scripts/lib/evidence-allocation.mjs';
import {theme} from '../scripts/lib/config.mjs';
import {planAndMeasureOutline,applyDomLayout} from '../scripts/lib/dom-layout-extractor.mjs';
import {renderPresentation,exportPresentation} from '../scripts/lib/ppt-renderer.mjs';
import {inspectPptxPackage} from '../scripts/lib/pptx-metadata.mjs';
import {auditDesignRequirements,nativeDesignPages} from '../scripts/lib/design-intent.mjs';
const ir=regulatoryFixture();
ir.slides=ir.slides.map(s=>allocateSlideEvidence(resolveSlideExpressions(classifySlideComposition(s))));
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'mint-rc4-design-'));
const measured=await planAndMeasureOutline(ir,theme,path.join(dir,'canvas.html'),path.join(dir,'render'));
assert.equal(measured.ir.slides.length,1);assert.deepEqual(measured.manifest.issues,[]);
const gate=auditDesignRequirements(measured.ir,measured.manifest);assert.deepEqual(gate.issues,[]);
const resolved=applyDomLayout(measured.ir,measured.manifest),{presentation}=await renderPresentation(resolved,theme),file=path.join(dir,'native.pptx');await exportPresentation(presentation,file);
const pkg=await inspectPptxPackage(file),xml=await pkg.zip.file(pkg.slides[0]).async('string');
assert.match(xml,/<p:cxnSp>/);
const require=createRequire(path.join(process.env.RUNTIME_NODE_MODULES,'package.json'));
const {FileBlob,PresentationFile}=await import(require.resolve('@oai/artifact-tool'));
const imported=await PresentationFile.importPptx(await FileBlob.load(file));
const nativeLayout=JSON.parse(await (await imported.slides.items[0].export({format:'layout'})).text());
fs.writeFileSync(path.join(dir,'native-layout.json'),JSON.stringify(nativeLayout,null,2));
const nativePng=await imported.export({slide:imported.slides.items[0],format:'png',scale:1});
fs.writeFileSync(path.join(dir,'native.png'),new Uint8Array(await nativePng.arrayBuffer()));
assert.deepEqual(artifactLayoutIssues(nativeLayout),[]);
const nativePages=nativeDesignPages([xml],resolved.slides.map(s=>s.id));
assert.deepEqual(auditDesignRequirements(resolved,measured.manifest,{nativePages}).issues,[]);
assert.equal(pkg.fullSlideImages.length,0);
for(const value of ['预计9月获批','11月至次年1月','验收完成后','+2个月','银行甲','银行乙','银行丙']) assert.ok(pkg.visibleText.replace(/\s/g,'').includes(value.replace(/\s/g,'')),value);
const missing=structuredClone(measured.manifest);missing.slides[0].modules.forEach(m=>m.primitives=m.primitives.filter(p=>p.primitive!=='time-range'));
assert.equal(auditDesignRequirements(resolved,missing).passed,false);
console.log(JSON.stringify({passed:true,dir,gate,nativeShapes:pkg.nativeShapes}));
