import assert from 'node:assert/strict';
import {designBriefHash,designBriefIssues,applyDesignBriefs,designAcceptanceIssues,designExecutionIssues,designBriefPreview,directorPlanIssues} from '../scripts/lib/execution-brief.mjs';
import {sceneLayoutCandidates,directorTopology} from '../scripts/lib/scene-plan.mjs';
import {planOutlinePages} from '../scripts/lib/outline-planner.mjs';
import {visualModuleMarkup} from '../scripts/lib/visual-primitives.mjs';
import {allocateSlideEvidence} from '../scripts/lib/evidence-allocation.mjs';
const scene={flow:'vertical',regions:['a','b'].map(id=>({id,role:'primary',relation:'stack',weight:'natural',moduleIds:[id]})),readingOrder:['a','b']};
const slides=['a','b'].map(id=>({id,role:'content',sectionId:'s',outlineItem:'1',decisionUnit:id,claim:'同一管理故事',modules:[{id,type:'text',text:'完整事实'+id}]}));
const ledger={sha256:'source',units:[{id:'f'}]};
const composition={flow:'banded',bands:[{id:'evidence',share:[70,80],columns:[2,1],moduleRefs:['a','b']}]};
const alternative={flow:'banded',bands:[{id:'focus',share:[30,40],columns:[1],moduleRefs:['a']},{id:'support',share:[45,55],columns:[1],moduleRefs:['b']}]};
const brief={canonicalLedgerHash:'source',decisionSystems:[{id:'a'},{id:'b'}],requirementsReview:{promptSha256:'prompt'},designBriefs:[{id:'story',decisionIds:['a','b'],sourceRefs:['f'],objective:'同页说明行动及其依据',fiveSecondMessage:'行动有完整证据支持',visualPurpose:'让相关证据靠近行动',copyGuidance:'清晰中文',colorSemantics:'主色强调行动',avoid:'不要因载体不同拆页',compositionPolicy:'flexible',carriers:[{moduleId:'a',purpose:'主要行动',priority:'P0'},{moduleId:'b',purpose:'支持证据',priority:'P1'}],scenePlan:scene,directorPlan:{fiveSecondMessage:'行动有完整证据支持',visualThesis:'主要行动由相邻证据直接证明',expectedFirstFocus:{objectRef:'a',reason:'这是管理层首先需要判断的行动'},completeComposition:composition,alternativeCompositions:[alternative],carrierBindings:[{moduleId:'a',expression:'text',regionId:'evidence',priority:'P0',visualTreatment:'primary-visual',copyBudget:{maxLines:3}},{moduleId:'b',expression:'text',regionId:'evidence',priority:'P1',visualTreatment:'supporting-evidence',copyBudget:{maxLines:3}}],metricEmphasis:[],semanticColors:[{targetId:'a',role:'highlight'}],bodyProof:[{moduleRefs:['a','b'],reason:'行动与证据共同证明标题'}],whitespaceIntent:{intentional:false,reason:null}}}]};
brief.designBriefs[0].takeaway=slides[0].claim;
brief.designBriefReview={status:'reviewed',canonicalLedgerHash:'source',designSha256:designBriefHash(brief)};
assert.deepEqual(designBriefIssues(brief,ledger,slides),[]);
assert.match(designBriefPreview(brief),/尚未固定页数/);
assert.ok(designBriefIssues({},ledger).includes('DESIGN_BRIEF_REQUIRED'));
const changed=structuredClone(brief);changed.designBriefs[0].objective='新目标';
assert.ok(designBriefIssues(changed,ledger,slides).includes('DESIGN_BRIEF_REVIEW_REQUIRED'));
assert.ok(designBriefIssues(brief,ledger,[slides[0],{...slides[1],sectionId:'other'}]).some(i=>i.includes('CROSS_SECTION')));
const candidates=sceneLayoutCandidates({scenePlan:scene,directorComposition:composition,directorAlternatives:[alternative]});
assert.equal(new Set(candidates.map(c=>directorTopology(c.directorComposition))).size,2);
assert.equal(sceneLayoutCandidates({scenePlan:scene,directorComposition:composition,directorAlternatives:[alternative],designCompositionPolicy:'user-fixed'}).length,1);
const result=await planOutlinePages(applyDesignBriefs(slides,brief),async p=>({passed:p.measuredSceneVariant==='director-alternative',issues:[],slides:[]}),{designBriefs:brief.designBriefs});
assert.equal(result.slides.length,1,'Related decision IDs must be measured together before pagination');
assert.equal(result.slides[0].modules.length,2);
assert.equal(result.slides[0].measuredSceneVariant,'director-alternative');
assert.equal(allocateSlideEvidence({...applyDesignBriefs(slides,brief)[0],modules:[{id:'a',type:'callout',semanticRole:'managementConclusion',visualPriority:'P2'}]}).modules[0].visualPriority,'P2','Legacy auto-priority must not override the reviewed design');
const split=slides.map(s=>({...s,designBriefId:'story'})),ir={slides:split,executionBrief:brief};
const review={designBriefs:[{id:'story',status:'accepted',firstFocusObserved:'行动',visualPurposeObserved:'邻近证据',compositionObserved:'双栏'}],chapter:{adjacentPages:[{before:'a',after:'b',reason:'measured-capacity',capacityAttemptIds:['1']}]}};
assert.ok(designAcceptanceIssues(review,ir,[{attemptId:'1',phase:'complete',passed:true,measured:true,candidate:{designBriefId:'story',modules:slides.flatMap(s=>s.modules)}}]).some(i=>i.includes('CAPACITY_CITATION_INVALID')));
review.chapter.adjacentPages[0].reason='independent-decisions';
assert.ok(designAcceptanceIssues(review,ir,[]).some(i=>i.includes('SPLIT_AS_INDEPENDENT')));
const module={id:'entities',expression:{variant:'entity-comparison'},data:{nodes:[{id:'n',entity:true,label:'测试对象',metrics:[{label:'预计规模',value:'688',unit:'亿元'}],metricPriorities:{'metric-0':'P0'}}]}};
const html=visualModuleMarkup(module);
assert.match(html,/data-vp-priority="P0"/);assert.match(html,/metric-value[^>]*>688/);assert.match(html,/metric-unit[^>]*>亿元/);
assert.equal((html.match(/688/g)||[]).length,1,'Do not duplicate metrics to satisfy coverage');
const metricBrief=structuredClone(brief);metricBrief.designBriefs[0].directorPlan.metricEmphasis=[{moduleId:'entities',nodeId:'n',field:'metric-0',priority:'P0'}];
assert.ok(designExecutionIssues({executionBrief:metricBrief,slides:[{id:'x',designBriefId:'story'}]},{slides:[{slideId:'x',modules:[]}]}).some(i=>i.includes('METRIC_UNIMPLEMENTED')));
const director=brief.designBriefs[0],modules=slides.flatMap(s=>s.modules);
const generic=structuredClone(director);generic.directorPlan.visualThesis='突出重点';assert.ok(directorPlanIssues(generic,modules).some(i=>i.includes('GENERIC_DIRECTOR_PLAN')));
const noFocus=structuredClone(director);noFocus.directorPlan.carrierBindings.forEach(b=>b.priority='P1');assert.ok(directorPlanIssues(noFocus,modules).some(i=>i.includes('NO_VISUAL_FOCUS')));
const mismatch=structuredClone(director);mismatch.directorPlan.carrierBindings[0].expression='funnel';assert.ok(directorPlanIssues(mismatch,modules).some(i=>i.includes('EXPRESSION_BINDING_MISMATCH')));
const flat=structuredClone(director);flat.directorPlan.carrierBindings.forEach(b=>b.priority='P0');assert.ok(directorPlanIssues(flat,modules).some(i=>i.includes('FLAT_HIERARCHY')));
const equivalent=structuredClone(director);equivalent.directorPlan.alternativeCompositions=[structuredClone(equivalent.directorPlan.completeComposition)];assert.ok(directorPlanIssues(equivalent,modules).some(i=>i.includes('EQUIVALENT_ALTERNATIVES')));
const context=structuredClone(director),contextModules=modules.map(m=>({...m,semanticRole:'context'}));assert.ok(directorPlanIssues(context,contextModules).some(i=>i.includes('CONTEXT_ONLY_STANDALONE')));
const unproved=structuredClone(director);unproved.directorPlan.bodyProof=[{moduleRefs:['b'],reason:'只引用辅助证据'}];assert.ok(directorPlanIssues(unproved,modules).some(i=>i.includes('UNPROVEN_VISUAL_THESIS')));
const whitespace=structuredClone(director);whitespace.directorPlan.whitespaceIntent={intentional:true,reason:null};assert.ok(directorPlanIssues(whitespace,modules).some(i=>i.includes('UNINTENTIONAL_WHITESPACE')));
const invalidShare=structuredClone(director);invalidShare.directorPlan.completeComposition.bands[0].share=[90,70];assert.ok(directorPlanIssues(invalidShare,modules).some(i=>i.includes('DIRECTOR_COMPOSITION_SHARE')));
const table=structuredClone(director),tableModule=[{id:'a',type:'table',semanticRole:'primaryEvidence',data:{headers:['项目'],rows:[['甲']]}}];table.directorPlan.completeComposition={flow:'banded',bands:[{id:'evidence',share:[70,80],columns:[1],moduleRefs:['a']}]};table.directorPlan.alternativeCompositions=[];table.directorPlan.carrierBindings=[{moduleId:'a',expression:'table',regionId:'evidence',priority:'P0',visualTreatment:'natural-table',copyBudget:{maxLines:3}}];table.directorPlan.bodyProof=[{moduleRefs:['a'],reason:'表格作为页面主证据'}];assert.ok(directorPlanIssues(table,tableModule).some(i=>i.includes('TABLE_DEFAULTING')));
console.log('design brief unit regressions passed');
