import assert from "node:assert/strict";
import { inferDataShape, routeExpression, resolveSlideExpressions, expressionSuitability, tableToChartData } from "../scripts/lib/expression-router.mjs";
import {chartDisplayModel} from '../scripts/lib/chart-display-model.mjs';
import {theme} from '../scripts/lib/config.mjs';

const unitInput={claim:'甲乙比较',semanticIntent:'comparison',modules:[{id:'m',type:'chart',data:{categories:['甲','乙'],unit:'k',series:[{name:'安装',values:[493.9,304.9]},{name:'使用',unit:'k',values:[219.4,131.5]}]}}]};
const withUnits=resolveSlideExpressions(unitInput).modules[0];
assert.deepEqual(withUnits.data.series.map(s=>s.displayUnit),['k','k']);
assert.deepEqual(withUnits.data.series.map(s=>s.values),unitInput.modules[0].data.series.map(s=>s.values));
const conflict=structuredClone(unitInput);conflict.modules[0].data.series[1].displayUnit='万人';
assert.throws(()=>resolveSlideExpressions(conflict),/CHART_UNIT_CONFLICT/);
const dots=chartDisplayModel(withUnits.data,withUnits.expression,1129,theme.palette);
assert.equal(new Set(dots.primitives.filter(p=>p.kind==='circle').map(p=>p.color)).size,2,'Emphasis cannot erase series identity');
const points=dots.primitives.filter(p=>p.kind==='circle'),labels=dots.primitives.filter(p=>p.role==='chartValue');
labels.forEach((label,i)=>{assert.match(label.text,/k$/);assert(Math.abs(label.x-points[i].x)<20,'Dot labels stay near the point');assert(label.x+label.width<=dots.width);});
const longUnits=chartDisplayModel({categories:['成本','收入'],series:[{name:'月度口径',displayUnit:'万美元 / 月',values:[16.38,53.4]}]},{variant:'variance-bar'},1000,theme.palette);
assert(longUnits.primitives.filter(p=>p.role==='chartValue').every(p=>p.width>125&&p.x+p.width<=1000),'Long units reserve label space without shrinking or stripping units');

const twoPeriods = { categories: ["Y1", "Y2"], series: [{ name: "收入", values: [80, 92] }] };
assert.equal(inferDataShape(twoPeriods).hasTime, true);
assert.equal(routeExpression({ semanticIntent: "trend", data: twoPeriods }).variant, "dumbbell");
assert.equal(routeExpression({ semanticIntent: "trend", data: { categories: ["Y1", "Y2", "Y3", "Y4", "Y5", "Y6", "Y7", "Y8"], series: [{ values: [1,2,3,4,5,6,7,8] }] } }).variant, "line");
assert.equal(routeExpression({ semanticIntent: "composition", data: { categories: ["A", "B"], series: [{ values: [30, 40] }] } }).variant, "sorted-bar");
assert.equal(routeExpression({ semanticIntent: "composition", data: { categories: ["A", "B"], series: [{ values: [30, 70] }], partToWhole: true, whole: 100 } }).variant, "doughnut");
assert.equal(routeExpression({ semanticIntent: "contribution", data: { categories: ["人力", "IT"], series: [{ values: [-10, -5] }], additiveBridge: true } }).variant, "waterfall");
assert.equal(routeExpression({ semanticIntent: "correlation", data: { categories: ["1", "2", "3"], series: [{ values: [1,2,3] }, { values: [4,5,6] }] } }).type, "table");
assert.equal(routeExpression({ semanticIntent: "process", type: "diagram", data: { nodes: [{id:1},{id:2}], edges: [{from:1,to:2}] } }).variant, "flow");
assert.equal(routeExpression({ semanticIntent: "trend", type: "callout", semanticRole: "managementConclusion", data: {} }).type, "callout");
const sameValues = { categories: ["A", "B", "C"], series: [{ name: "实际", values: [80, 72, 55] }] };
assert.equal(routeExpression({ managementQuestion: "谁最高？", semanticIntent: "ranking", type: "chart", data: sameValues }).variant, "sorted-bar");
assert.equal(routeExpression({ managementQuestion: "谁完成目标？", semanticIntent: "variance", type: "chart", data: { ...sameValues, hasTarget: true } }).variant, "variance-bar");
assert.equal(routeExpression({ managementQuestion: "逐项核对数字", semanticIntent: "lookup", type: "chart", data: sameValues }).type, "table");
const costTable = { exactLookup: true, values: [["科目", "压降后", "压降额"], ["人力", "308.6", "203.3"], ["IT", "21.7", "89.6"]] };
assert.equal(routeExpression({ managementQuestion: "主要压降项是什么？", claim: "人力与IT是主要压降项", semanticIntent: "comparison", type: "table", data: costTable }).type, "chart");
assert.equal(routeExpression({ managementQuestion: "逐项核对成本明细", semanticIntent: "lookup", type: "table", data: costTable }).type, "table");
assert.equal(routeExpression({ semanticIntent: "process", type: "text", data: {} }).type, "text");
const invalid = { id: "S1", modules: [{ id: "m1", type: "chart", dataShape: inferDataShape(twoPeriods), expression: { type: "chart", variant: "line" } }] };
assert.equal(expressionSuitability(invalid).length, 1);
const focused = resolveSlideExpressions({ claim: "人力与IT是主要压降项", managementQuestion: "主要压降项是什么？", semanticIntent: "ranking", modules: [{ id: "m", type: "chart", semanticRole: "primaryEvidence", data: { categories: ["人力", "IT", "职场"], series: [{ name: "压降额", values: [203.3, 89.6, 42.8] }] } }] });
assert.deepEqual(focused.modules[0].expression.focusCategories, ["人力", "IT"]);
assert.equal(focused.modules[0].expression.annotationIntent, "rank");
console.log(JSON.stringify({ passed: true, tests: 18 }));
const separated = { headers: ['项目', '金额'], rows: [['人力', 203.3], ['IT', 89.6], ['职场', 42.8]] };
assert.deepEqual(tableToChartData(separated).categories, ['人力', 'IT', '职场']);
assert.deepEqual(tableToChartData(separated).series, [{name:'金额',values:[203.3,89.6,42.8],unitKind:'magnitude',displayUnit:''}]);
assert.equal(inferDataShape(separated).categoryCount, 3);
assert.throws(() => tableToChartData({headers:['项目','金额'],rows:[['A',null],['B',2]]}), /MISSING_CHART_VALUE/);
assert.throws(() => tableToChartData({headers:['项目','金额'],rows:[['A','待确认'],['B',2]]}), /MISSING_CHART_VALUE/);
assert.deepEqual(tableToChartData({headers:['项目','实际','预算'],rows:[['A',0,2],['B',1,3]]}).series.map(s=>s.values), [[0,1],[2,3]]);
const fourPairs={categories:['A','B','C','D'],series:[{values:[1,2,3,4]},{values:[2,3,4,5]}]};
assert.equal(inferDataShape(fourPairs).observationCount,4);
assert.equal(routeExpression({semanticIntent:'correlation',data:fourPairs}).type,'table');
assert.equal(routeExpression({semanticIntent:'process',type:'text',data:{nodes:[{id:'a'},{id:'b'}],edges:[{from:'a',to:'b'}]}}).type,'diagram');
const stages={categories:['触达','申请','放款'],series:[{name:'人数',values:[1000,400,100]}],samePopulation:true};
assert.equal(routeExpression({managementQuestion:'哪些环节流失最多？',semanticIntent:'conversion',type:'table',data:stages}).variant,'stage-bars');
assert.throws(()=>routeExpression({semanticIntent:'conversion',data:{...stages,samePopulation:false}}),/STAGE_POPULATION_REVIEW_REQUIRED/);
assert.equal(routeExpression({managementQuestion:'成本明细中谁压降最多？',semanticIntent:'ranking',type:'table',data:costTable}).type,'chart','明细不是查数的同义词');
