import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { createRequire } from "node:module";
import { pathToFileURL } from "node:url";
import { snapshotPpt } from "../scripts/lib/ppt-state.mjs";

if (!process.env.RUNTIME_NODE_MODULES) throw new Error("RUNTIME_NODE_MODULES is required");
const require = createRequire(path.join(process.env.RUNTIME_NODE_MODULES, "package.json"));
const { FileBlob, Presentation, PresentationFile } = await import(pathToFileURL(require.resolve("@oai/artifact-tool")).href);
const folder = fs.mkdtempSync(path.join(os.tmpdir(), "mint-ppt-read-")), file = path.join(folder, "read.pptx");
const deck = Presentation.create({ slideSize: { width: 1920, height: 1080 } }), slide = deck.slides.add();
const textbox = slide.shapes.add({ geometry: "textbox", name: "mint|text|scene.title", position: { left: 80, top: 80, width: 600, height: 100 }, fill: "none", line: { fill: "none", width: 0 } }); textbox.text = "标题";
const table = slide.tables.add({ rows: 2, columns: 2, left: 80, top: 220, width: 500, height: 220, values: [["A", "B"], [1, 2]] }); table.name = "mint|table|tables.main";
const chart = slide.charts.add("bar", { position: { left: 650, top: 220, width: 500, height: 300 }, categories: ["A", "B"], series: [{ name: "数值", values: [1, 2] }] }); chart.name = "mint|chart|charts.main";
const image = slide.images.add({ dataUrl: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=", alt: "像素", position: { left: 1220, top: 220, width: 100, height: 100 }, fit: "contain" }); image.name = "mint|media|media.main";
await (await PresentationFile.exportPptx(deck)).save(file);
const imported = await PresentationFile.importPptx(await FileBlob.load(file));
const records = (await imported.inspect({ kind: "textbox,table,chart,image", include: "id,slide,name,bbox,text,rows,cols,preview,chartType,title,alt", maxChars: 20000 })).ndjson.trim().split("\n").filter(Boolean).map(JSON.parse);
const byName = Object.fromEntries(records.map(item => [item.name, item]));
assert.equal(byName["mint|text|scene.title"].text, "标题");
const resolvedTable = imported.resolve(byName["mint|table|tables.main"].id), resolvedChart = imported.resolve(byName["mint|chart|charts.main"].id), resolvedImage = imported.resolve(byName["mint|media|media.main"].id);
assert.equal(String(resolvedTable.getCell(0, 0).text), "A");
const firstSeries = resolvedChart.series.getItemAt(0);
assert.deepEqual([...firstSeries.values], [1, 2]);
assert.deepEqual([...firstSeries.categories], ["A", "B"]);
assert.equal(Math.round(resolvedImage.frame.width), 100);
const state = await snapshotPpt(file, { includeImageData: true }), imageState = state.objects.find(item => item.name === "mint|media|media.main"), chartState = state.objects.find(item => item.name === "mint|chart|charts.main"), tableState = state.objects.find(item => item.name === "mint|table|tables.main");
assert.match(imageState.dataUrl, /^data:image\/png;base64,/); assert.equal(imageState.mediaHash.length, 64); assert.deepEqual(chartState.series[0].values, [1, 2]); assert.equal(tableState.values[1][1], "2");
fs.rmSync(folder, { recursive: true, force: true });
console.log(JSON.stringify({ passed: true, tests: 9 }));
