import assert from 'node:assert/strict';
import { planOutlinePages } from '../scripts/lib/outline-planner.mjs';
const slide = (id, outlineItem) => ({ id, role: 'content', outlineItem, claim: '完整结论', modules: [{ id: `m-${id}`, type: 'text', text: id }] });
const measure = async page => ({ passed: page.modules.length <= 2, issues: page.modules.length > 2 ? ['overflow'] : [] });
const merged = await planOutlinePages([slide('a', '1'), slide('b', '1'), slide('c', '2'), slide('d', '3')], measure);
assert.equal(merged.slides.length, 3);
assert.equal(merged.slides[0].modules.length, 2);
const split = await planOutlinePages([slide('a', '1'), slide('b', '1'), slide('c', '1')], measure);
assert.equal(split.slides.length, 2);
assert.equal(split.slides[0].modules.length, 2, 'equal page counts must not strand a short first page');
assert.equal(split.slides[1].outlineSplit.continuationOf, split.slides[0].id);
assert.equal(split.slides[0].capacityProof.fullOutlineFits, false);
assert.equal(split.slides[0].claim, '完整结论', 'splitting must not hide the original conclusion in notes');
const table={id:'costs',type:'table',data:{headers:['科目','值'],rows:[['总计',3],['甲',1],['乙',2]],rowGroups:[{label:'概览',start:0,end:1},{label:'明细',start:1,end:3}],rowEvidenceRefs:[['total'],['a'],['b']]},evidenceRefs:['total','a','b'],visibleFacts:[{sourceUnitId:'total',text:'总计'},{sourceUnitId:'a',text:'甲'},{sourceUnitId:'b',text:'乙'}]};
const natural=await planOutlinePages([{...slide('summary','1'),modules:[{id:'policy',type:'text',text:'启动原则',evidenceGroup:'policy'},table]}],async p=>({passed:p.modules.reduce((sum,m)=>sum+(m.data?.rows?.length||1),0)<=2,issues:['capacity']}));
assert.equal(natural.slides.length,2);
assert.deepEqual(natural.slides[0].modules.map(m=>m.id),['policy','costs-group-1']);
assert.deepEqual(natural.slides.flatMap(s=>s.modules.flatMap(m=>m.data?.rows||[])),table.data.rows);
console.log('outline-planner: 5 assertions passed');
const scored=await planOutlinePages([{...slide('rank','1'),modules:[{id:'one'},{id:'two'}]}],async p=>({passed:true,slides:[{compositionScore:p.measuredComposition==='primary-rail'?5:0}]}));
assert.equal(scored.slides[0].measuredComposition,'primary-rail','compare feasible layouts instead of choosing the first pass');
