import assert from 'node:assert/strict';
import {projectPresentationCopy,presentationCopyHash,validatePresentationCopy,copyTextIssues,humanCopyChecks,humanCopyReviewIssues} from '../scripts/lib/presentation-copy.mjs';
import {auditVisibleFactContent} from '../scripts/lib/source-coverage.mjs';
const ir={presentationCopyVersion:1,executionBrief:{},slides:[{id:'s',claim:'银行覆盖本地客户',modules:[{id:'m',type:'diagram',text:'视觉关键词 | schema',data:{nodes:[{id:'bank',entity:true,label:'raw field',keywords:['Local Network'],identity:'old | data',metrics:['old metric'],text:'old source'}],edges:[]},displayCopy:{title:'银行概况',nodes:[{id:'bank',name:'银行甲',headline:'本地合作网络',primaryMetrics:['总资产100亿元'],summary:'服务本地客户。'}],edges:[]}}]}]};
ir.executionBrief.presentationCopyReview={status:'reviewed',canonicalLedgerHash:'canonical',copySha256:presentationCopyHash(ir)};
assert.deepEqual(validatePresentationCopy(ir,{sha256:'canonical'}),[]);
const projected=projectPresentationCopy(ir),node=projected.slides[0].modules[0].data.nodes[0];
assert.equal(node.label,'银行甲');assert.equal(node.keywords,undefined);assert.equal(projected.slides[0].modules[0].text,'');assert.deepEqual(projectPresentationCopy(projected),projected);
assert.equal(ir.slides[0].modules[0].text,'视觉关键词 | schema','Source IR must not be mutated');
for(const [text,code] of [['银行 | 规模','COPY_PIPE_METADATA'],['**重点**','COPY_MARKDOWN'],['semanticRole: risk','COPY_SCHEMA_LEAK'],['视觉关键词','COPY_INSTRUCTION_LEAK']]) assert.ok(copyTextIssues(text).includes(code));
assert.ok(copyTextIssues('Local Network',{instructionOnlyPhrases:['Local Network']}).length);
assert.deepEqual(copyTextIssues('Co-operative Bank of Kenya 总资产约6880亿肯尼亚先令'),[]);
const missing=structuredClone(ir);delete missing.slides[0].modules[0].displayCopy;
assert.ok(validatePresentationCopy(missing,{sha256:'canonical'}).some(i=>i.includes('DISPLAY_COPY_REQUIRED')));
const changed=structuredClone(ir);changed.slides[0].modules[0].displayCopy.nodes[0].summary='新文案';
assert.ok(validatePresentationCopy(changed,{sha256:'canonical'}).includes('PRESENTATION_COPY_REVIEW_REQUIRED'));
changed.slides[0].modules[0].displayCopy.nodes[0].primaryMetrics=['a','b','c'];assert.throws(()=>projectPresentationCopy(changed),/PROFILE_PRIMARY_METRIC_LIMIT/);
const review={humanPresentationCopy:{...Object.fromEntries(humanCopyChecks.map(k=>[k,'pass'])),evidence:'逐项审阅实际可见文字。'}};
assert.deepEqual(humanCopyReviewIssues(review),[]);review.humanPresentationCopy.languageMix='fail';assert.ok(humanCopyReviewIssues(review).length);
const unit={id:'u',text:'预计全年收入777美元，采用agent banking',visibility:'required-visible',requiredComponents:['预计全年收入777美元','代理银行'],componentReview:{status:'reviewed',sourceText:'预计全年收入777美元，采用agent banking',terminology:[{source:'agent banking',display:'代理银行',reason:'translation'}]}};
const model={sourceUnits:[unit]},deck={slides:[{id:'s',role:'content',modules:[{id:'m',text:'预计全年收入777美元，采用代理银行',visibleFacts:[{sourceUnitId:'u',text:'代理银行'}]}]}]};
assert.equal(auditVisibleFactContent(model,deck).passed,true);
for(const removed of ['预计','美元','777']) {const bad=structuredClone(deck);bad.slides[0].modules[0].text=bad.slides[0].modules[0].text.replace(removed,'');assert.equal(auditVisibleFactContent(model,bad).passed,false);}
delete unit.componentReview.terminology;assert.equal(auditVisibleFactContent(model,deck).passed,false);
const numbered={sourceUnits:[{id:'n',text:'2）预计额外3个月',visibility:'required-visible',requiredComponents:['预计额外3个月'],componentReview:{status:'reviewed',sourceText:'2）预计额外3个月'}}]};
const numberedDeck={slides:[{id:'s',modules:[{id:'m',text:'预计额外3个月',visibleFacts:[{sourceUnitId:'n',text:'预计额外3个月'}]}]}]};
assert.equal(auditVisibleFactContent(numbered,numberedDeck).passed,true,'Outline numbering is not a business value');
numberedDeck.slides[0].modules[0].text='预计额外个月';assert.equal(auditVisibleFactContent(numbered,numberedDeck).passed,false);
console.log('Presentation copy: explicit projection, leakage, binding review, translation and human gate passed');
