import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {createRequire} from 'node:module';
import {domainCases} from './fixtures/rc5-domain-cases.mjs';
import {classifySlideComposition} from '../scripts/lib/composition-classifier.mjs';
import {resolveSlideExpressions} from '../scripts/lib/expression-router.mjs';
import {allocateSlideEvidence} from '../scripts/lib/evidence-allocation.mjs';
import {theme} from '../scripts/lib/config.mjs';
import {planAndMeasureOutline,applyDomLayout} from '../scripts/lib/dom-layout-extractor.mjs';
import {renderPresentation,exportPresentation} from '../scripts/lib/ppt-renderer.mjs';
import {inspectPptxPackage} from '../scripts/lib/pptx-metadata.mjs';
import {artifactLayoutIssues} from '../scripts/lib/artifact-layout.mjs';
const folder=fs.mkdtempSync(path.join(os.tmpdir(),'mint-rc5-scenes-'));
const input={slides:domainCases().map(s=>allocateSlideEvidence(resolveSlideExpressions(classifySlideComposition(s))))};
input.executionBrief={decisionSystems:input.slides.map(s=>({id:s.decisionUnit,managementQuestion:s.managementQuestion}))};
const planned=await planAndMeasureOutline(input,theme,path.join(folder,'canvas.html'),path.join(folder,'canvas'));
const {ir,manifest}=planned;
fs.writeFileSync(path.join(folder,'capacity-attempts.json'),JSON.stringify(planned.measurements,null,2));
assert.equal(ir.slides.length,10,'ten independent moderate decision systems remain ten complete pages');
for(const slide of ir.slides) assert.equal(slide.capacityProof.fullOutlineFits,true);
fs.writeFileSync(path.join(folder,'manifest.json'),JSON.stringify(manifest,null,2));
assert.deepEqual(manifest.issues,[],folder);
const range=manifest.slides[1].modules[0].primitives.find(p=>p.primitive==='time-range');
assert.ok(range.borderLeftWidth>0&&range.borderRightWidth>0,'both time-window boundaries measured');
const shortTable=manifest.slides[5].modules[0].table;
assert.ok(shortTable.rect.height<350,'two rows cannot expand to full-page height');
const note=manifest.slides[5].modules[1].contentBounds;
const tableGap=Math.max(0,note.left-shortTable.rect.left-shortTable.rect.width);
assert.ok(tableGap<80,`natural short table must release its empty split track; gap=${tableGap}`);
const resolved=applyDomLayout(ir,manifest),{presentation}=await renderPresentation(resolved,theme),pptx=path.join(folder,'scenes.pptx');
await exportPresentation(presentation,pptx);
const pkg=await inspectPptxPackage(pptx);assert.equal(pkg.slides.length,10);assert.equal(pkg.fullSlideImages.length,0);
assert.match(await pkg.zip.file(pkg.slides[1]).async('string'),/primitive:time-range[^"<]*\|right/);
const require=createRequire(path.join(process.env.RUNTIME_NODE_MODULES,'package.json'));
const {FileBlob,PresentationFile}=await import(require.resolve('@oai/artifact-tool'));
const imported=await PresentationFile.importPptx(await FileBlob.load(pptx)),issues=[];
for(const [i,slide] of imported.slides.items.entries()) {
  const layout=JSON.parse(await (await slide.export({format:'layout'})).text());
  issues.push(...artifactLayoutIssues(layout).map(issue=>`${i+1}: ${issue}`));
  fs.writeFileSync(path.join(folder,`native-${i+1}.png`),new Uint8Array(await (await imported.export({slide,format:'png',scale:1})).arrayBuffer()));
}
fs.writeFileSync(path.join(folder,'native-audit.json'),JSON.stringify({issues},null,2));
assert.deepEqual(issues,[],folder);
console.log(JSON.stringify({folder,slides:10,candidates:planned.measurements.length,status:'technical-passed-awaiting-executive-visual-review',scope:'fixed synthetic IR through browser capacity planning; not A/B/C fresh Planner runs'}));
